sudo: required
dist: xenial
language: node_js
node_js:
  - '10.15.1'

addons:
  chrome: stable
services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g angular-cli codacy-coverage
  - npm install

script:
  - ng lint
  - ng build --prod hazdev-ng-geoserve-output
  - ng build --prod --delete-output-path false --base-href /geoserve/
  - ng test hazdev-ng-geoserve-output --watch=false --code-coverage
  - ng test earthquake-geoserve-ui --watch=false --code-coverage
  - ng e2e

after_success:
  - cat coverage/lcov.info | codacy-coverage --verbose
